const phones = [
    // ── Apple ──
    {
        id: 1,
        name: 'iPhone 15 Pro Max',
        brand: 'Apple',
        price: 1199,
        image: 'https://placehold.co/400x400/1a1a2e/ffffff?text=iPhone+15+Pro',
        specs: { processor: 'A17 Pro Bionic', ram: '8 GB', battery: '4422 mAh' },
        colors: ['#4a4a4f', '#f5f5f0', '#3b3b4f', '#8b6f47'],
        colorNames: ['Titanium Black', 'White Titanium', 'Blue Titanium', 'Natural Titanium'],
        storageOptions: ['128 GB', '256 GB', '512 GB', '1 TB'],
        badge: 'New',
        rating: 4.8,
        reviews: 5200,
    },
    {
        id: 2,
        name: 'iPhone 15',
        brand: 'Apple',
        price: 799,
        image: 'https://placehold.co/400x400/2d3a8c/ffffff?text=iPhone+15',
        specs: { processor: 'A16 Bionic', ram: '6 GB', battery: '3877 mAh' },
        colors: ['#1a1a1a', '#d4e4f7', '#f5e6d3', '#c5e8c5'],
        colorNames: ['Black', 'Blue', 'Pink', 'Green'],
        storageOptions: ['128 GB', '256 GB', '512 GB'],
        rating: 4.6,
        reviews: 8100,
    },
    {
        id: 3,
        name: 'iPhone 14',
        brand: 'Apple',
        price: 599,
        image: 'https://placehold.co/400x400/1a2744/ffffff?text=iPhone+14',
        specs: { processor: 'A15 Bionic', ram: '6 GB', battery: '3279 mAh' },
        colors: ['#1a1a1a', '#e0d4f7', '#e8e8e8'],
        colorNames: ['Midnight', 'Purple', 'Starlight'],
        storageOptions: ['128 GB', '256 GB', '512 GB'],
        rating: 4.5,
        reviews: 12400,
    },

    // ── Samsung ──
    {
        id: 4,
        name: 'Galaxy S24 Ultra',
        brand: 'Samsung',
        price: 1299,
        image: 'https://placehold.co/400x400/16213e/ffffff?text=Galaxy+S24',
        specs: { processor: 'Snapdragon 8 Gen 3', ram: '12 GB', battery: '5000 mAh' },
        colors: ['#2d2d2d', '#e8e4de', '#c9b896', '#5c5c8a'],
        colorNames: ['Phantom Black', 'Cream', 'Amber', 'Violet'],
        storageOptions: ['256 GB', '512 GB', '1 TB'],
        badge: 'Best Seller',
        rating: 4.7,
        reviews: 7400,
    },
    {
        id: 5,
        name: 'Galaxy S24+',
        brand: 'Samsung',
        price: 999,
        image: 'https://placehold.co/400x400/1e3a5f/ffffff?text=Galaxy+S24%2B',
        specs: { processor: 'Exynos 2400', ram: '12 GB', battery: '4900 mAh' },
        colors: ['#2d2d2d', '#d4c6a5', '#5c5c8a'],
        colorNames: ['Onyx Black', 'Amber Yellow', 'Cobalt Violet'],
        storageOptions: ['256 GB', '512 GB'],
        rating: 4.5,
        reviews: 3200,
    },
    {
        id: 6,
        name: 'Galaxy Z Fold 5',
        brand: 'Samsung',
        price: 1799,
        image: 'https://placehold.co/400x400/0d1b2a/ffffff?text=Z+Fold+5',
        specs: { processor: 'Snapdragon 8 Gen 2', ram: '12 GB', battery: '4400 mAh' },
        colors: ['#2c3e50', '#f5e6d3', '#3498db'],
        colorNames: ['Phantom Black', 'Cream', 'Icy Blue'],
        storageOptions: ['256 GB', '512 GB', '1 TB'],
        badge: 'Foldable',
        rating: 4.4,
        reviews: 2800,
    },

    // ── Google ──
    {
        id: 7,
        name: 'Pixel 9 Pro',
        brand: 'Google',
        price: 999,
        image: 'https://placehold.co/400x400/0f3460/ffffff?text=Pixel+9+Pro',
        specs: { processor: 'Tensor G4', ram: '16 GB', battery: '5060 mAh' },
        colors: ['#1a1a1a', '#f0ede8', '#b5c9b7', '#d4a6a6'],
        colorNames: ['Obsidian', 'Porcelain', 'Wintergreen', 'Rose Quartz'],
        storageOptions: ['128 GB', '256 GB', '512 GB'],
        badge: 'AI Camera',
        rating: 4.6,
        reviews: 4100,
    },
    {
        id: 8,
        name: 'Pixel 8a',
        brand: 'Google',
        price: 499,
        image: 'https://placehold.co/400x400/1a3c5a/ffffff?text=Pixel+8a',
        specs: { processor: 'Tensor G3', ram: '8 GB', battery: '4492 mAh' },
        colors: ['#1a1a1a', '#87ceeb', '#b5c9b7'],
        colorNames: ['Obsidian', 'Bay', 'Aloe'],
        storageOptions: ['128 GB', '256 GB'],
        badge: 'Best Value',
        rating: 4.4,
        reviews: 6200,
    },

    // ── OnePlus ──
    {
        id: 9,
        name: 'OnePlus 12',
        brand: 'OnePlus',
        price: 799,
        image: 'https://placehold.co/400x400/1a1a2e/e0e0e0?text=OnePlus+12',
        specs: { processor: 'Snapdragon 8 Gen 3', ram: '12 GB', battery: '5400 mAh' },
        colors: ['#1a1a1a', '#284d28'],
        colorNames: ['Silky Black', 'Flowy Emerald'],
        storageOptions: ['256 GB', '512 GB'],
        rating: 4.5,
        reviews: 3800,
    },
    {
        id: 10,
        name: 'OnePlus Nord 4',
        brand: 'OnePlus',
        price: 399,
        image: 'https://placehold.co/400x400/2c3e50/e0e0e0?text=Nord+4',
        specs: { processor: 'Snapdragon 7+ Gen 3', ram: '8 GB', battery: '5500 mAh' },
        colors: ['#1a1a1a', '#c0c0c0'],
        colorNames: ['Obsidian Midnight', 'Silver Wing'],
        storageOptions: ['128 GB', '256 GB'],
        badge: 'Budget Pick',
        rating: 4.3,
        reviews: 4500,
    },

    // ── Xiaomi ──
    {
        id: 11,
        name: 'Xiaomi 14 Ultra',
        brand: 'Xiaomi',
        price: 899,
        image: 'https://placehold.co/400x400/16213e/e0e0e0?text=Xiaomi+14+Ultra',
        specs: { processor: 'Snapdragon 8 Gen 3', ram: '16 GB', battery: '5300 mAh' },
        colors: ['#1a1a1a', '#f5f5f0'],
        colorNames: ['Black', 'White'],
        storageOptions: ['256 GB', '512 GB', '1 TB'],
        badge: 'Leica Camera',
        rating: 4.6,
        reviews: 2100,
    },
    {
        id: 12,
        name: 'Xiaomi 14 Pro',
        brand: 'Xiaomi',
        price: 699,
        image: 'https://placehold.co/400x400/1e3a5f/e0e0e0?text=Xiaomi+14+Pro',
        specs: { processor: 'Snapdragon 8 Gen 3', ram: '12 GB', battery: '4880 mAh' },
        colors: ['#1a1a1a', '#f5f5f0', '#2a4d3c'],
        colorNames: ['Black', 'White', 'Jade Green'],
        storageOptions: ['256 GB', '512 GB'],
        rating: 4.4,
        reviews: 3100,
    },

    // ── Sony ──
    {
        id: 13,
        name: 'Xperia 1 VI',
        brand: 'Sony',
        price: 1099,
        image: 'https://placehold.co/400x400/0f3460/e0e0e0?text=Xperia+1+VI',
        specs: { processor: 'Snapdragon 8 Gen 3', ram: '12 GB', battery: '5000 mAh' },
        colors: ['#1a1a1a', '#c0c0c0', '#2e4053'],
        colorNames: ['Black', 'Platinum Silver', 'Khaki Green'],
        storageOptions: ['256 GB', '512 GB'],
        rating: 4.3,
        reviews: 1800,
    },

    // ── Nothing ──
    {
        id: 14,
        name: 'Nothing Phone (2a)',
        brand: 'Nothing',
        price: 349,
        image: 'https://placehold.co/400x400/0d1b2a/ffffff?text=Nothing+2a',
        specs: { processor: 'Dimensity 7200 Pro', ram: '8 GB', battery: '5000 mAh' },
        colors: ['#1a1a1a', '#f5f5f0'],
        colorNames: ['Black', 'White'],
        storageOptions: ['128 GB', '256 GB'],
        badge: 'Unique Design',
        rating: 4.3,
        reviews: 5400,
    },

    // ── Motorola ──
    {
        id: 15,
        name: 'Motorola Edge 50 Ultra',
        brand: 'Motorola',
        price: 799,
        image: 'https://placehold.co/400x400/1a2744/ffffff?text=Edge+50+Ultra',
        specs: { processor: 'Snapdragon 8s Gen 3', ram: '16 GB', battery: '4500 mAh' },
        colors: ['#2c3e50', '#8b4513', '#f0ede8'],
        colorNames: ['Forest Grey', 'Peach Fuzz', 'Nordic Wood'],
        storageOptions: ['256 GB', '512 GB', '1 TB'],
        rating: 4.2,
        reviews: 1200,
    },

    // ── ASUS ──
    {
        id: 16,
        name: 'ROG Phone 8 Pro',
        brand: 'ASUS',
        price: 1099,
        image: 'https://placehold.co/400x400/0d0d1a/ff4444?text=ROG+Phone+8',
        specs: { processor: 'Snapdragon 8 Gen 3', ram: '24 GB', battery: '5500 mAh' },
        colors: ['#0d0d1a', '#e0e0e0'],
        colorNames: ['Phantom Black', 'Rebel Grey'],
        storageOptions: ['256 GB', '512 GB', '1 TB'],
        badge: 'Gaming',
        rating: 4.5,
        reviews: 2300,
    },
]

export default phones
