const phones = [
    {
        id: 1,
        name: 'iPhone 15 Pro Max',
        brand: 'Apple',
        price: 1199,
        image: 'https://placehold.co/400x400/1a1a2e/ffffff?text=iPhone+15+Pro',
        specs: {
            processor: 'A17 Pro Bionic',
            ram: '8 GB',
            battery: '4422 mAh',
        },
        colors: ['#4a4a4f', '#f5f5f0', '#3b3b4f', '#8b6f47'],
        colorNames: ['Titanium Black', 'White Titanium', 'Blue Titanium', 'Natural Titanium'],
        storageOptions: ['128 GB', '256 GB', '512 GB', '1 TB'],
    },
    {
        id: 2,
        name: 'Samsung Galaxy S24 Ultra',
        brand: 'Samsung',
        price: 1299,
        image: 'https://placehold.co/400x400/16213e/ffffff?text=Galaxy+S24',
        specs: {
            processor: 'Snapdragon 8 Gen 3',
            ram: '12 GB',
            battery: '5000 mAh',
        },
        colors: ['#2d2d2d', '#e8e4de', '#c9b896', '#5c5c8a'],
        colorNames: ['Phantom Black', 'Cream', 'Amber', 'Violet'],
        storageOptions: ['256 GB', '512 GB', '1 TB'],
    },
    {
        id: 3,
        name: 'Google Pixel 9 Pro',
        brand: 'Google',
        price: 999,
        image: 'https://placehold.co/400x400/0f3460/ffffff?text=Pixel+9+Pro',
        specs: {
            processor: 'Tensor G4',
            ram: '16 GB',
            battery: '5060 mAh',
        },
        colors: ['#1a1a1a', '#f0ede8', '#b5c9b7', '#d4a6a6'],
        colorNames: ['Obsidian', 'Porcelain', 'Wintergreen', 'Rose Quartz'],
        storageOptions: ['128 GB', '256 GB', '512 GB'],
    },
    {
        id: 4,
        name: 'OnePlus 12',
        brand: 'OnePlus',
        price: 799,
        image: 'https://placehold.co/400x400/1a1a2e/e0e0e0?text=OnePlus+12',
        specs: {
            processor: 'Snapdragon 8 Gen 3',
            ram: '12 GB',
            battery: '5400 mAh',
        },
        colors: ['#1a1a1a', '#284d28'],
        colorNames: ['Silky Black', 'Flowy Emerald'],
        storageOptions: ['256 GB', '512 GB'],
    },
    {
        id: 5,
        name: 'Xiaomi 14 Pro',
        brand: 'Xiaomi',
        price: 699,
        image: 'https://placehold.co/400x400/16213e/e0e0e0?text=Xiaomi+14+Pro',
        specs: {
            processor: 'Snapdragon 8 Gen 3',
            ram: '12 GB',
            battery: '4880 mAh',
        },
        colors: ['#1a1a1a', '#f5f5f0', '#2a4d3c'],
        colorNames: ['Black', 'White', 'Jade Green'],
        storageOptions: ['256 GB', '512 GB'],
    },
    {
        id: 6,
        name: 'Sony Xperia 1 VI',
        brand: 'Sony',
        price: 1099,
        image: 'https://placehold.co/400x400/0f3460/e0e0e0?text=Xperia+1+VI',
        specs: {
            processor: 'Snapdragon 8 Gen 3',
            ram: '12 GB',
            battery: '5000 mAh',
        },
        colors: ['#1a1a1a', '#c0c0c0', '#2e4053'],
        colorNames: ['Black', 'Platinum Silver', 'Khaki Green'],
        storageOptions: ['256 GB', '512 GB'],
    },
]

export default phones
